# You can also set the token via environment variable DISCORD_BOT_TOKEN for better security
token: YOUR-BOT-TOKEN # Enter your discord bot token.
ip: YOUR.SERVER.IP # Enter the IP address or domain of the server you want to watch. You can also add a port, if the server does not use the default port (25565)
name: "YOUR MINECRAFT SERVER NAME" # Enter the display name of the server.
# Set to 1 to enable detailed debug output. Includes server status and error details.
debug: 0
refresh-interval: 30 # Refresh interval for server status updates in seconds
# For security reasons, debug mode should only be enabled during troubleshooting, not in production.
# if you're done with editing this config change file name to "config.yml"
